### PR TITLE
[WIP] .net standard 1.3 port

### LINKED ISSUE #121: DNX Support
Adding this library to an ASP.NET 5 causes a runtime error of not finding the `libsodium.dll` file. So it seems the `Baseclass.Contrib.Nuget.Output` package doesn't do it's job anymore?

### LINKED ISSUE #148: .net Core Support
Will this library work on .net Core?  If not, are there any plans to get it working?

### PR DESCRIPTION
**Pull request by BurningEnlightenment**
Hello everyone,

@ektrah (more or less willingly 😋) and me are currently working towards providing an official binary distribution of libsodium for .net through the new `runtimes/native/` nuget machinery (see jedisct1/libsodium#504).
I've done the initial work to support this new nuget package which has the potential to eliminate the `Baseclass.Contrib.Nuget.Output` dependency. Furthermore I've made the (implementation of the) libsodium abstractions compatible with the .net standard 1.3. The public API hasn't been touched by this and I tried to make the necessary implementation changes as nonintrusive as possible (from my point of view, for more details see the commit messages; if there're better solutions to any of the compat fixes I will integrate them).
As part of the .net standard port I had to replace your `DynamicInvoke` solution with traditional `DllImport`s and addressed the native bitness issue of the full .net framework the same way Microsoft did for `Microsoft.Data.Sqlite` and `SQLitePCL.raw`: For a net46 application, the `libsodium` nuget package puts the `libsodium.dll` binaries in the corresponding `x86` and `x64` directories and at runtime the correct binary gets loaded by `RuntimeShim.PinDllImportLibrary()` through `LoadLibraryEx()`. (see also [this stackoverflow answer](https://stackoverflow.com/questions/8836093/how-can-i-specify-a-dllimport-path-at-runtime/8861895#8861895))

My initial tests of the above method have been working very well so far, but I haven't had time to take a look at Mono or think about shadow copying. The tests haven't been ported yet, but I'm not sure how far NUnit's .net core support has progressed (still need to read http://www.alteridem.net/2017/05/04/test-net-core-nunit-vs2017/)

TODO:
- [ ] comply with any changes requested
- [ ] decide whether this should replace the existing project or live in its own package
- [x] finish remaining work tracked over here: [.net core port github project](https://github.com/BurningEnlightenment/libsodium-net/projects/1)
- [x] wait for jedisct1/libsodium#504

fixes #148 
fixes #121 
(probably) obsoletes #150
/xref jedisct1/libsodium#504

[instructions on how to build the libsodium nuget package](https://github.com/jedisct1/libsodium/tree/master/packaging/dotnet-core)

### CODE REVIEW

**Comment by BurningEnlightenment** [comment]
travis build failures are due to xbuild not understanding the new project format 😓

**Comment by BurningEnlightenment** [comment]
FYI I've derived issues from the actionable TODOs in my github fork and organized them in a [github project](https://github.com/BurningEnlightenment/libsodium-net/projects/1) which will hopefully provide better trackability of the remaining work.

**Comment by BurningEnlightenment** [comment]
@bitbeans @adamcaudill do you want me to preserve the old project and the DynamicInvoke hack? Or can I go ahead and replace the old one?

**Comment by adamcaudill** [comment]
The `DynamicInvoke` hack is very much that, a hack. It was done to make it easier to deal with `libsodium-net` being AnyCPU, and `libsodium` being CPU-specific, which is further complicated by NuGet's awful handling of unmanaged DLLs. It's made use for full .NET applications work well, give or take some that had issues with ASP.NET. 

Today, things are more complex, and `DynamicInvoke` isn't the right solution anymore. So, here's how I see it:
* We can't break applications that work today. If someone is using it now, and it works, it should keep working.
* It should keep working with Mono.
* It should work on the widest range of .NET versions as possible.
* Ideally, it should work with .NET Core.

Change is needed, we just need to make sure that we follow these priorities when making changes.

**Comment by BurningEnlightenment** [comment]
I've done some testing of this stuff on (arch-)linux and my results were:
- *building* the net46 assemblies on linux requires Mono 5.0 due to the new project format, but using them with any Mono version supporting net46 should be fine
- the dotnet sdk cannot build cannot build the net46 target on linux (not an issue due to Mono)
- tests pass with mono and .net core on linux and windows without any errors 🎉 

> We can't break applications that work today. If someone is using it now, and it works, it should keep working.

I removed the `DynamicInvoke` and `LazyInvoke` classes which might break applications illegally relying on them, is this a problem?

**Comment by adamcaudill** [comment]
Those classes were never meant to be used outside of the library; I am fine with removal. If anyone was using them, they can grab the code from git history, and use them directly.

**Comment by BurningEnlightenment** [comment]
I think this is ready to be reviewed.

Please note that the travis build failure on mac osx with dotnet core happens during the package restore step which seems to overwhelm the travis worker.

**Comment by jedisct1** [comment]
Also: https://github.com/bfriesen/LibsodiumDotNetStandardSpike /cc @bfriesen

**Comment by danielcrenna** [comment]
@BurningEnlightenment What is the status of this relative to the main branch? I have this working in .NET Standard 2.0 with minor adjustments, though the 1.0.12-preview-01 `libsodium` package is not resolving correctly, and so will only work on Windows builds.

**Comment by adamcaudill** [comment]
I've merged the change - we may need to make some further changes to get things where we want them, but at least we can get this into master so we are making some progress.

**Pull request merged**
