### PR TITLE
libsodium 1.0.6

### LINKED ISSUE #119: update dll`s to libsodium 1.04
https://github.com/jedisct1/libsodium/blob/master/ChangeLog

### PR DESCRIPTION
**Pull request by bitbeans**
- Fixed exception messages in PublicKeyBox
- Updated the libsodium dll's to 1.0.6
- Added sodium_increment
- Added sodium_compare
- Added crypto_aead_aes256gcm_*

Fixes #119

### CODE REVIEW

**Comment by bitbeans** [comment]
we need to update the libsodium dll before travis will work

**Comment by fraga** [comment]
Hi @adamcaudill can you please verify this?

**Comment by bitbeans** [comment]
the commit already includes the 1.0.6 dlls

**Comment by fraga** [comment]
@bitbeans can you verify if your tests runs fine?

Travis failed with 

```
5) Test Failure : Tests.VersionTest.SodiumVersionStringTest

     String lengths are both 5. Strings differ at index 4.

  Expected: "1.0.6"

  But was:  "1.0.3"
```

I believe you must also change the build scripts in travis to account for libsodium 1.0.6

**Comment by adamcaudill** [comment]
The version of libsodium needs to be updated in `travis-build-libsodium.sh` - then it looks like it's good to merge.

**Comment by adamcaudill** [comment]
Well, this is unexpected. Tests are fine on Linux, but fail on OSX - with a rather unusual error:

```
Tests run: 192, Errors: 2, Failures: 0, Inconclusive: 0, Time: 17.598771 seconds
  Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0

Errors and Failures:
1) Test Error : Tests.SecretAeadAesTest.AesAeadWithAdditionalDataTest
   System.ExecutionEngineException : SIGILL
  at (wrapper managed-to-native) DynamicDllInvokeType:crypto_aead_aes256gcm_encrypt (intptr,long&,byte[],long,byte[],long,byte[],byte[],byte[])
  at (wrapper delegate-invoke) <Module>:invoke_int__this___intptr_long&_byte[]_long_byte[]_long_byte[]_byte[]_byte[] (intptr,long&,byte[],long,byte[],long,byte[],byte[],byte[])
  at Sodium.SecretAeadAes.Encrypt (System.Byte[] message, System.Byte[] nonce, System.Byte[] key, System.Byte[] additionalData) [0x00000] in <filename unknown>:0 
  at Tests.SecretAeadAesTest.AesAeadWithAdditionalDataTest () [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 

2) Test Error : Tests.SecretAeadAesTest.AesAeadWithoutAdditionalDataTest
   System.ExecutionEngineException : SIGILL
  at (wrapper managed-to-native) DynamicDllInvokeType:crypto_aead_aes256gcm_encrypt (intptr,long&,byte[],long,byte[],long,byte[],byte[],byte[])
  at (wrapper delegate-invoke) <Module>:invoke_int__this___intptr_long&_byte[]_long_byte[]_long_byte[]_byte[]_byte[] (intptr,long&,byte[],long,byte[],long,byte[],byte[],byte[])
  at Sodium.SecretAeadAes.Encrypt (System.Byte[] message, System.Byte[] nonce, System.Byte[] key, System.Byte[] additionalData) [0x00000] in <filename unknown>:0 
  at Tests.SecretAeadAesTest.AesAeadWithoutAdditionalDataTest () [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
```

There seems to be a large number of issues that can cause this error - but it's odd that it's only happening on OSX.

**Comment by fraga** [comment]
Glad you're back @adamcaudill :)

Yeah that is why I thought lets first update libsodium and double check if tests pass.

I will also test here but for now someone with osx to test?

**Comment by bitbeans** [comment]
I can`t test OSX :(

**Comment by jedisct1** [comment]
Is it actually OSX, or the fact that it was tested on a Mac with an old CPU?

aes256gcm is only available on CPUs with hardware-accelerated AES. On older CPUs, the instruction doesn't exist, so you get `SIGILL`.

`crypto_aead_aes256gcm_is_available()` must be called to check whether aes256gcm is available or not.

**Comment by bitbeans** [comment]
```crypto_aead_aes256gcm_is_available``` is failing on my local system with the current stable release 1.0.6. But with the master (1.0.7) it just runs fine.

**Comment by bitbeans** [comment]
@jedisct1 is there already a release date for 1.0.7?

**Comment by jedisct1** [comment]
Very soon!

Meanwhile, you can check out the `stable` branch.

**Comment by fraga** [comment]
thanks @jedisct1 @bitbeans looks good :)

**Comment by bitbeans** [comment]
@jedisct1 very soon == tomorrow :+1:

**Comment by bitbeans** [comment]
@adamcaudill @fraga can you check the pull request again please?

**Comment by fraga** [comment]
Looks good for me

**Comment by adamcaudill** [comment]
Thanks! Sorry it took so long to get this one done.

**Pull request merged**
