### PR TITLE
libsodium 1.0.12

### PR DESCRIPTION
**Pull request by adamcaudill**
Bump libsodium to latest.

**NOTE:** This also increases the .NET version to 4.6 - as older versions aren't supported, should bump up to a modern version.

@fraga @bitbeans - Please review.

### CODE REVIEW

**Comment by adamcaudill** [comment]
Once change is approved, I'll push out a beta, and if no issues, push out a new release quickly.

**Comment by bitbeans** [comment]
https://github.com/adamcaudill/libsodium-net/blob/master/Tests/PasswordHashTest.cs#L419 fails

**Comment by adamcaudill** [comment]
Thanks for catching that! I was having issues with my dev VM and missed it. Added new test to test the minimum output size, updated the existing check to bump the minimum size, updated the copyright, and bumped the version number. All tests pass locally.

**Comment by hoffin** [comment]
Hi, is there a reason why this isn't getting merged? 1.0.13 is out

**Comment by adamcaudill** [comment]
Merging this into master. Some of this is already outdated, but we need to get this in to be able to get this moving again.

**Pull request merged**
