### PR TITLE
SealedBox

### PR DESCRIPTION
**Pull request by bitbeans**

### CODE REVIEW

**Comment by bitbeans** [comment]
Sorry wrong issue number: Fixes #104

**Comment by fraga** [comment]
Hi @bitbeans can you actually rebase your branch and then force a push?
it would then clear out the first commit you have "update from source"

**Comment by bitbeans** [comment]
sorry, it`s now clear :)

**Comment by adamcaudill** [comment]
Thanks! Much appreciated.

I'm wondering about the name - the naming of this is always going to be a bit confusing, just because of what it it, but I wonder if `SealedPublicKeyBox` would make more sense to users than `SealedBox` - thoughts?

**Comment by bitbeans** [comment]
Hmm, maybe you are right :)
Shortly i thought about something like: *Seal* instead of *Create* but ... this would also be confusing.

I will rename it (SealedBox to SealedPublicKeyBox) and push again, i also will update the gitbook after merging.

**Pull request merged**
